language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fenrir28/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -t fenrir28/docker-react npm run test